/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QL_GUI;

import QL_DAO.DAO_CThdXuat;
import QL_DAO.DAO_HDXuat;
import QL_DAO.DAO_KhachHang;
import QL_DAO.DAO_LoaiSp;
import QL_DAO.DAO_SanPham;
import QL_DAO.DAO_nhanVien;
import QL_POJO.cthdXuat;
import QL_POJO.HDXuat;
import QL_POJO.LoaiSP;
import QL_POJO.SanPham;
import QL_POJO.KhachHang;
import QL_POJO.NhanVien;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEC
 */
public class F_banHang extends javax.swing.JFrame {

    /**
     * Creates new form F_banHang
     */
    DefaultTableModel dtm_tbloaisp = new DefaultTableModel();
    DefaultTableModel dtm_tbchiloaisp = new DefaultTableModel();
    DefaultTableModel dtm_giohang = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    public F_banHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] tieudeloaisp = {"Mã Loại", "Tên Loại"};
        dtm_tbloaisp.setColumnIdentifiers(tieudeloaisp);
        String[] tieudectsp = {"Mã SP", "Tên SP", "Loại SP", "Màu SP", "Đời SP", "Số lượng còn", "Đơn giá", "Tình Trạng"};
        dtm_tbchiloaisp.setColumnIdentifiers(tieudectsp);
        String[] tieudeKH2 = {"Mã SP", "Tên SP", "Màu SP", "Đời SP", "Số lượng mua", "Đơn giá SP"};
        dtm_giohang.setColumnIdentifiers(tieudeKH2);
        hienthiloaisp();
        hienthidsKH();
        hienthidsnv();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbloaiSP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbctloaiSP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttenSP = new javax.swing.JTextField();
        txtngayBan = new javax.swing.JTextField();
        txtdonGiaSP = new javax.swing.JTextField();
        txtmaSP = new javax.swing.JTextField();
        txtmauSP = new javax.swing.JTextField();
        txtdoiSP = new javax.swing.JTextField();
        txtslMua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnxemCTKH = new javax.swing.JButton();
        txttenNV = new javax.swing.JTextField();
        cbotenKH = new javax.swing.JComboBox<>();
        cbomaKH = new javax.swing.JComboBox<>();
        cbomaNV = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbgiohang = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JTextField();
        btnthanhToan = new Swing.button();
        btnthemHang = new Swing.button();
        btnxoagiohang = new Swing.button();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tbloaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbloaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbloaiSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbloaiSP);

        tbctloaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbctloaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbctloaiSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbctloaiSP);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Loại sản phẩm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Chi tiết loại sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Tên KH");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Mã nhân viên");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Ngày bán");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Đơn giá SP");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Mã SP");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Màu SP");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Đời");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Số lượng mua");

        txttenSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtngayBan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtdonGiaSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtmaSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtmauSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtdoiSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txtslMua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Mã KH");

        btnxemCTKH.setText("Xem thông tin");
        btnxemCTKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemCTKHActionPerformed(evt);
            }
        });

        cbotenKH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbotenKHItemStateChanged(evt);
            }
        });

        cbomaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbomaNVItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cbotenKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnxemCTKH)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(cbomaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtdonGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtngayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(66, 66, 66)
                                        .addComponent(txtmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtmauSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtdoiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtslMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(cbomaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(277, 277, 277))))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbomaKH, cbomaNV, txtdoiSP, txtdonGiaSP, txtmaSP, txtmauSP, txtngayBan, txtslMua, txttenNV});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbomaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txtmauSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdoiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtslMua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(btnxemCTKH)
                            .addComponent(cbotenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbomaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txtngayBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdonGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbgiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbgiohang);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Tổng tiền :");

        txttongtien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        btnthanhToan.setText("Thanh toán");
        btnthanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnthanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnthemHang.setText("Thêm giỏ hàng");
        btnthemHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemHangActionPerformed(evt);
            }
        });

        btnxoagiohang.setText("Xóa giỏ hàng");
        btnxoagiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoagiohangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnthemHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoagiohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoagiohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(761, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemHangActionPerformed
        if (txtslMua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Số Lượng Mua");
        } else {
            cbotenKH.setEnabled(false);
            cbomaKH.setEnabled(false);
            cbomaNV.setEnabled(false);
            txttenNV.setEnabled(false);
            txtngayBan.setEnabled(false);
            hienthiGioHang();
            capnhattongtien();
        }

    }//GEN-LAST:event_btnthemHangActionPerformed

    private void tbloaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbloaiSPMouseClicked
        int indexrow = tbloaiSP.getSelectedRow();
        int maloaisp;
        maloaisp = (Integer) tbloaiSP.getValueAt(indexrow, 0);
        hienthiClickdsctxemay(maloaisp);
    }//GEN-LAST:event_tbloaiSPMouseClicked

    private void tbctloaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbctloaiSPMouseClicked
        String pattern = "dd/MM/yyyy";
        DateFormat df = new SimpleDateFormat(pattern);
        Date today = Calendar.getInstance().getTime();
        int indexrow = tbctloaiSP.getSelectedRow();
        txtmaSP.setText(String.valueOf(tbctloaiSP.getValueAt(indexrow, 0)));
        txttenSP.setText((String) tbctloaiSP.getValueAt(indexrow, 1));
        txtmauSP.setText((String) tbctloaiSP.getValueAt(indexrow, 3));
        txtdoiSP.setText((String) tbctloaiSP.getValueAt(indexrow, 4));
        txtdonGiaSP.setText(String.valueOf(tbctloaiSP.getValueAt(indexrow, 6)));
        txtngayBan.setText(df.format(today));
    }//GEN-LAST:event_tbctloaiSPMouseClicked

    private void cbotenKHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbotenKHItemStateChanged
        cbomaKH.removeAllItems();
        String tenKH = cbotenKH.getSelectedItem().toString();
        ArrayList<Integer> dsmaKH = DAO_KhachHang.laymaKH(tenKH);
        for (Integer KH : dsmaKH) {
            cbomaKH.addItem(KH.toString());
        }
    }//GEN-LAST:event_cbotenKHItemStateChanged

    private void btnxemCTKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemCTKHActionPerformed
        F_KhachHang kh = new F_KhachHang();
        kh.setTextFieldValue(Integer.parseInt(cbomaKH.getSelectedItem().toString()));
        kh.setVisible(true);
    }//GEN-LAST:event_btnxemCTKHActionPerformed

    private void cbomaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbomaNVItemStateChanged
        int manv = Integer.parseInt(cbomaNV.getSelectedItem().toString());
        String tennv = DAO_nhanVien.laytenNV(manv);
        txttenNV.setText(tennv);
    }//GEN-LAST:event_cbomaNVItemStateChanged

    private void btnthanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhToanActionPerformed
        if (tbgiohang.getRowCount() == 0 || txttongtien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm");
        } else {
            themhdXuat();
            ThemcthoadonXuat();
            JOptionPane.showMessageDialog(this, "Thanh toán thành công");
            cbotenKH.setEnabled(true);
            cbomaKH.setEnabled(true);
            cbomaNV.setEnabled(true);
            txttenNV.setEnabled(true);
            txtngayBan.setEnabled(true);
            cbotenKH.setEnabled(true);
            cbomaKH.setEnabled(true);
            cbomaNV.setEnabled(true);
            txttenSP.setText("");
            txtngayBan.setText("");
            txtdonGiaSP.setText("");
            txtmaSP.setText("");
            txtmauSP.setText("");
            txtdoiSP.setText("");
            txtslMua.setText("");
            txttongtien.setText("");
            dtm_giohang.setRowCount(0);
            tbgiohang.setModel(dtm_giohang);

        }

    }//GEN-LAST:event_btnthanhToanActionPerformed

    private void btnxoagiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoagiohangActionPerformed
        int clickrow = tbgiohang.getSelectedRow();
        dtm_giohang.removeRow(clickrow);
    }//GEN-LAST:event_btnxoagiohangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_banHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_banHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_banHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_banHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_banHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.button btnthanhToan;
    private Swing.button btnthemHang;
    private javax.swing.JButton btnxemCTKH;
    private Swing.button btnxoagiohang;
    private javax.swing.JComboBox<String> cbomaKH;
    private javax.swing.JComboBox<String> cbomaNV;
    private javax.swing.JComboBox<String> cbotenKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbctloaiSP;
    private javax.swing.JTable tbgiohang;
    private javax.swing.JTable tbloaiSP;
    private javax.swing.JTextField txtdoiSP;
    private javax.swing.JTextField txtdonGiaSP;
    private javax.swing.JTextField txtmaSP;
    private javax.swing.JTextField txtmauSP;
    private javax.swing.JTextField txtngayBan;
    private javax.swing.JTextField txtslMua;
    private javax.swing.JTextField txttenNV;
    private javax.swing.JTextField txttenSP;
    private javax.swing.JTextField txttongtien;
    // End of variables declaration//GEN-END:variables

    private void hienthiloaisp() {
        ArrayList<LoaiSP> dsloaisp = DAO_LoaiSp.layDanhSachLoaiSP();
        dtm_tbloaisp.setRowCount(0);
        for (LoaiSP loaiSP : dsloaisp) {
            Vector<Object> v = new Vector<Object>();
            v.add(loaiSP.getMaloaiSP());
            v.add(loaiSP.getTenloaiSP());
            dtm_tbloaisp.addRow(v);
        }
        tbloaiSP.setModel(dtm_tbloaisp);
    }

    private void hienthiClickdsctxemay(int maloaisp) {
        ArrayList<SanPham> dssp = DAO_SanPham.layDanhSachSP(maloaisp);
        dtm_tbchiloaisp.setRowCount(0);
        for (SanPham sp : dssp) {
            Vector<Object> v = new Vector<Object>();
            v.add(sp.getMaSp());
            v.add(sp.getTenSp());
            v.add(sp.getLoaiSp());
            v.add(sp.getMausp());
            v.add(sp.getDoiSp());
            v.add(sp.getSoluongcon());
            v.add(sp.getDongia());
            v.add(sp.getTinhTrang());
            dtm_tbchiloaisp.addRow(v);
        }
        tbctloaiSP.setModel(dtm_tbchiloaisp);
    }

    private void hienthidsKH() {
        ArrayList<KhachHang> dstenKH = DAO_KhachHang.layDStenKH();
        for (KhachHang KH : dstenKH) {
            cbotenKH.addItem(String.valueOf(KH.getHoTenKH()));

        }
    }

    private void hienthidsnv() {
        ArrayList<NhanVien> dsNV = DAO_nhanVien.layDanhSachNV();
        for (NhanVien nv : dsNV) {
            cbomaNV.addItem(String.valueOf(nv.getMaNV()));
        }
    }

    private boolean kiemtratrungsanpham(SanPham sp) {
        boolean kq = false;
        int sodong = tbgiohang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            if (sp.getMaSp() == (Integer) tbgiohang.getValueAt(i, 0)
                    && (sp.getTenSp().trim().equals(tbgiohang.getValueAt(i, 1).toString().trim())) == true) {
                kq = true;

            }
        }
        return kq;
    }

    private void hienthiGioHang() {
        boolean kq;
        SanPham sp = new SanPham();
        sp.setMaSp(Integer.parseInt(txtmaSP.getText()));
        sp.setTenSp(txttenSP.getText());
        sp.setMausp(txtmauSP.getText());
        sp.setDoiSp(txtdoiSP.getText());
        sp.setSoluongcon(Integer.parseInt(txtslMua.getText()));
        sp.setDongia(Integer.parseInt(txtdonGiaSP.getText()));
        int sodong = tbgiohang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            // khởi tạo giỏ hàng
            if (tbgiohang.getValueAt(i, 0) == null && tbgiohang.getValueAt(i, 1) == null) {
                Vector<Object> v = new Vector<Object>();
                v.add(sp.getMaSp());
                v.add(sp.getTenSp());
                v.add(sp.getMausp());
                v.add(sp.getDoiSp());
                v.add(sp.getSoluongcon());
                v.add(sp.getDongia());
                dtm_giohang.addRow(v);
                tbgiohang.setModel(dtm_giohang);
            } else {
                kq = kiemtratrungsanpham(sp);
                if (kq == true) {
                    for (int k = 0; k < sodong; k++) {
                        if (sp.getMaSp() == (Integer) tbgiohang.getValueAt(k, 0)
                                && (sp.getTenSp().trim().equals(tbgiohang.getValueAt(k, 1).toString().trim())) == true) {
                            tbgiohang.setValueAt((Integer) tbgiohang.getValueAt(k, 4)
                                    + sp.getSoluongcon(), k, 4);
                        }
                    }

                } else {
                    Vector<Object> v = new Vector<Object>();
                    v.add(sp.getMaSp());
                    v.add(sp.getTenSp());
                    v.add(sp.getMausp());
                    v.add(sp.getDoiSp());
                    v.add(sp.getSoluongcon());
                    v.add(sp.getDongia());
                    dtm_giohang.addRow(v);
                    tbgiohang.setModel(dtm_giohang);
                }
            }

        }

    }

    private void capnhattongtien() {
        int tongtienhd = 0;
        int sodong = tbgiohang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            tongtienhd += (Integer) tbgiohang.getValueAt(i, 4) * (Integer) tbgiohang.getValueAt(i, 5);
        }
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        String str1 = currencyVN.format(tongtienhd);
        txttongtien.setText(str1);
    }

    private int laytongtien() {
        int tongtienhd = 0;
        int sodong = tbgiohang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            tongtienhd += (Integer) tbgiohang.getValueAt(i, 4) * (Integer) tbgiohang.getValueAt(i, 5);
        }
        return tongtienhd;
    }

    private void themhdXuat() {
        HDXuat hdx = new HDXuat();
        hdx.setMaKH(Integer.parseInt(cbomaKH.getSelectedItem().toString()));
        hdx.setMaNV(Integer.parseInt(cbomaNV.getSelectedItem().toString()));
        try {
            hdx.setNgayban(sdf.parse(txtngayBan.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(F_quanKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        hdx.settongtienhdxuat(laytongtien());
        DAO_HDXuat.them(hdx);
    }

    private void ThemcthoadonXuat() {
        cthdXuat cthdx = new cthdXuat();
        int sodong = tbgiohang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            cthdx.setMaHDXuat(DAO_HDXuat.laymaHD());
            cthdx.setMaSp((Integer) tbgiohang.getValueAt(i, 0));
            cthdx.setSoLuongXuat((Integer) tbgiohang.getValueAt(i, 4));
            cthdx.setDonGiaXuat((Integer) tbgiohang.getValueAt(i, 5));
            DAO_CThdXuat.themcthdn(cthdx);
        }
    }
}
