/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QL_GUI;
import QL_DAO.DAO_CThdNhap;
import QL_DAO.DAO_nhanVien;
import QL_DAO.DAO_nhaCC;
import QL_DAO.DAO_HDNhap;
import QL_DAO.DAO_SanPham;
import QL_DAO.DAO_LoaiSp;
import QL_POJO.CthdNhap;
import QL_POJO.NhanVien;
import QL_POJO.nhaCC;
import QL_POJO.HDNhap;
import QL_POJO.SanPham;
import QL_POJO.LoaiSP;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NEC
 */
public class F_quanKho extends javax.swing.JFrame {

    /**
     * Creates new form F_quanKho
     */
    DefaultTableModel dtm = new DefaultTableModel();
    DefaultTableModel dtm1 = new DefaultTableModel();
    DefaultTableModel dtm2 = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    public F_quanKho() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] tieudeLoaiSp = {"Mã Loại SP","Tên Loại SP"};
        dtm.setColumnIdentifiers(tieudeLoaiSp);
        String[] tieudeKH1 = {"Mã SP", "Tên SP","Loại SP","Màu SP","Đời SP","Số lượng còn","Đơn giá","Tình Trạng"};
        dtm1.setColumnIdentifiers(tieudeKH1);
        String[] tieudeKH2 = {"Mã SP","Tên SP","Màu Xe","Đời Xe","Số lượng nhập","Đơn giá nhập"};
        dtm2.setColumnIdentifiers(tieudeKH2);
        hienthiloaisp();
        hienthidsnv();
        hienthidsNCC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CbomaNV = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtngaynhap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmasp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmauXe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDoiXe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtslNhap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDonGiaNhap = new javax.swing.JTextField();
        btnnhaphang = new javax.swing.JButton();
        cbonhaCC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttenSP = new javax.swing.JTextField();
        btnthemhang = new javax.swing.JButton();
        txttennhaCC = new javax.swing.JTextField();
        txttenNV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbloaisp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbctSP = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbctdathang = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txttongtiennhap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin đơn đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        CbomaNV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CbomaNV.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbomaNVItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Ngày Nhập");

        txtngaynhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Mã SP");

        txtmasp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Màu SP");

        txtmauXe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Đời ");

        txtDoiXe.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("SL nhập");

        txtslNhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Đơn giá nhập");

        txtDonGiaNhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        btnnhaphang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnnhaphang.setText("Nhập hàng");
        btnnhaphang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhaphangActionPerformed(evt);
            }
        });

        cbonhaCC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbonhaCCItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Mã nhà CC");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Mã NV");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Tên SP");

        txttenSP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        btnthemhang.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnthemhang.setText("Thêm hàng");
        btnthemhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemhangActionPerformed(evt);
            }
        });

        txttennhaCC.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        txttenNV.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnnhaphang)
                        .addGap(18, 18, 18)
                        .addComponent(btnthemhang))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(63, 63, 63)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CbomaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbonhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txttennhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmauXe)
                    .addComponent(txtDoiXe)
                    .addComponent(txtslNhap)
                    .addComponent(txtmasp, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CbomaNV, cbonhaCC, txtDoiXe, txtDonGiaNhap, txtmasp, txtmauXe, txtngaynhap, txtslNhap});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txttenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbonhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txttennhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CbomaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtmauXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDoiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtslNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDonGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnhaphang)
                            .addComponent(btnthemhang))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin kho hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbloaisp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbloaisp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbloaispMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbloaisp);

        tbctSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbctSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbctSPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbctSP);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Thông tin từng loại");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết hóa đơn đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        tbctdathang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbctdathang);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Tổng tiền nhập");

        txttongtiennhap.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(40, 40, 40)
                .addComponent(txttongtiennhap, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txttongtiennhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbloaispMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbloaispMouseClicked
        int indexrow = tbloaisp.getSelectedRow();
        int maloaisp;
        maloaisp= (Integer)tbloaisp.getValueAt(indexrow, 0) ;
        hienthiClickdsctxemay(maloaisp);
//        hienthixemay();
    }//GEN-LAST:event_tbloaispMouseClicked

    private void tbctSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbctSPMouseClicked
        String pattern = "dd/MM/yyyy";
        DateFormat df = new SimpleDateFormat(pattern);
        Date today = Calendar.getInstance().getTime();        
        int indexrow = tbctSP.getSelectedRow();
         txtmasp.setText(String.valueOf(tbctSP.getValueAt(indexrow, 0)));
         txttenSP.setText((String) tbctSP.getValueAt(indexrow, 1));
         txtmauXe.setText((String) tbctSP.getValueAt(indexrow, 3));
         txtDoiXe.setText((String) tbctSP.getValueAt(indexrow, 4));
         txtngaynhap.setText(df.format(today));
    }//GEN-LAST:event_tbctSPMouseClicked

    private void btnthemhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemhangActionPerformed
        if (txtslNhap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Số Lượng Nhập");
        }
        if (txtDonGiaNhap.getText().isEmpty()) {
             JOptionPane.showMessageDialog(this, "Vui Lòng Nhập Đơn Giá Nhập");
        }
         hienthiGioHang();
         capnhattongtien();
    }//GEN-LAST:event_btnthemhangActionPerformed

    private void btnnhaphangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhaphangActionPerformed
        themhdNhap();
        Themcthoadonnhap();
        JOptionPane.showMessageDialog(this, "Nhập hàng thành công");
    }//GEN-LAST:event_btnnhaphangActionPerformed

    private void CbomaNVItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbomaNVItemStateChanged
        int manv = Integer.parseInt(CbomaNV.getSelectedItem().toString());
        String tennv =DAO_nhanVien.laytenNV(manv);
        txttenNV.setText(tennv);
    }//GEN-LAST:event_CbomaNVItemStateChanged

    private void cbonhaCCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbonhaCCItemStateChanged
        int manhacc = Integer.parseInt(cbonhaCC.getSelectedItem().toString());
        String maNCC = DAO_nhaCC.laytennhaCC(manhacc);
        txttennhaCC.setText(maNCC);
    }//GEN-LAST:event_cbonhaCCItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_quanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_quanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_quanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_quanKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_quanKho().setVisible(true);
            }
        });
    }

    private void hienthiloaisp() {
         ArrayList<LoaiSP> dsloaisp = DAO_LoaiSp.layDanhSachLoaiSP();
        dtm.setRowCount(0);
        for (LoaiSP loaiSP : dsloaisp) {
            Vector<Object> v = new Vector<Object>();
            v.add(loaiSP.getMaloaiSP());
            v.add(loaiSP.getTenloaiSP());
            dtm.addRow(v);
        }
        tbloaisp.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbomaNV;
    private javax.swing.JButton btnnhaphang;
    private javax.swing.JButton btnthemhang;
    private javax.swing.JComboBox<String> cbonhaCC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbctSP;
    private javax.swing.JTable tbctdathang;
    private javax.swing.JTable tbloaisp;
    private javax.swing.JTextField txtDoiXe;
    private javax.swing.JTextField txtDonGiaNhap;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txtmauXe;
    private javax.swing.JTextField txtngaynhap;
    private javax.swing.JTextField txtslNhap;
    private javax.swing.JTextField txttenNV;
    private javax.swing.JTextField txttenSP;
    private javax.swing.JTextField txttennhaCC;
    private javax.swing.JTextField txttongtiennhap;
    // End of variables declaration//GEN-END:variables

    private void hienthiClickdsctxemay(int maloaisp) {
        ArrayList<SanPham> dssp = DAO_SanPham.layDanhSachSP(maloaisp);
        dtm1.setRowCount(0);
        for (SanPham sp : dssp) {
            Vector<Object> v = new Vector<Object>();
            v.add(sp.getMaSp());
            v.add(sp.getTenSp());
            v.add(sp.getLoaiSp());
            v.add(sp.getMausp());
            v.add(sp.getDoiSp());
            v.add(sp.getSoluongcon());
            v.add(sp.getDongia());
            v.add(sp.getTinhTrang());
            dtm1.addRow(v);
        }
        tbctSP.setModel(dtm1);
    }
     private void hienthidsnv() {
        ArrayList<NhanVien> dsNV = DAO_nhanVien.layDanhSachNV();
        for (NhanVien nv : dsNV) {
            CbomaNV.addItem(String.valueOf(nv.getMaNV())); 
        }
      }
     private void hienthidsNCC() {
        ArrayList<nhaCC> dsnhaCC = DAO_nhaCC.layDanhSachnhaCC();
        for (nhaCC nhacc : dsnhaCC) {
            cbonhaCC.addItem(String.valueOf(nhacc.getMaNCC()));
            
        }
      }
     private void themhdNhap()
     {
         HDNhap hdn = new HDNhap();
         hdn.setMaNCC(Integer.parseInt(cbonhaCC.getSelectedItem().toString()) );
         hdn.setMaNV(Integer.parseInt(CbomaNV.getSelectedItem().toString()));
         try {
            hdn.setNgaynhap(sdf.parse(txtngaynhap.getText()) );
        } catch (ParseException ex) {
            Logger.getLogger(F_quanKho.class.getName()).log(Level.SEVERE, null, ex);
        }
        hdn.setTongtienhdnhap(laytongtien());
         DAO_HDNhap.them(hdn);
     }
      private void Themcthoadonnhap() {
        CthdNhap cthdn = new CthdNhap();
        int sodong = tbctdathang.getRowCount();
         for (int i = 0; i < sodong; i++) {
            cthdn.setMaHDNhap(DAO_HDNhap.laymaHD());
            cthdn.setMaSp((Integer)tbctdathang.getValueAt(i, 0));
            cthdn.setSoLuongNhap((Integer)tbctdathang.getValueAt(i, 4));
            cthdn.setDonGia((Integer)tbctdathang.getValueAt(i, 5));
            DAO_CThdNhap.themcthdn(cthdn);
         }
       
    }
      private void hienthiGioHang() {
        SanPham gh = new SanPham();
        int a = Integer.parseInt(txtslNhap.getText());
        int b = Integer.parseInt(txtDonGiaNhap.getText());
        int c = a*b;
  
        gh.setMaSp(Integer.parseInt(txtmasp.getText()));
        gh.setTenSp(txttenSP.getText());
        gh.setMausp(txtmauXe.getText());
        gh.setDoiSp(txtDoiXe.getText());
        gh.setSoluongcon(Integer.parseInt(txtslNhap.getText()));
        gh.setDongia(Integer.parseInt(txtDonGiaNhap.getText()));
        Vector<Object> v = new Vector<Object>();
        v.add(gh.getMaSp()); 
        v.add(gh.getTenSp()); 
        v.add(gh.getMausp()); 
        v.add(gh.getDoiSp()); 
        v.add(gh.getSoluongcon()); 
        v.add(gh.getDongia()); 
        dtm2.addRow(v);
        tbctdathang.setModel(dtm2);
        
    }
    private void capnhattongtien() {
        int tongtienhd = 0;
        int sodong = tbctdathang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            tongtienhd += (Integer) tbctdathang.getValueAt(i, 4)*(Integer) tbctdathang.getValueAt(i, 5);
        }
        Locale localeVN = new Locale("vi", "VN");
        NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
        String str1 = currencyVN.format(tongtienhd);
        txttongtiennhap.setText(str1);
        
      
    }
    private int laytongtien() {
        int tongtienhd = 0;
        int sodong = tbctdathang.getRowCount();
        for (int i = 0; i < sodong; i++) {
            tongtienhd += (Integer) tbctdathang.getValueAt(i, 4)*(Integer) tbctdathang.getValueAt(i, 5);
        }
       return tongtienhd;
    }
}
